<?php

/**
 * @file
 * Defining ajax callbacks, registering CKEditor plugin and including default views.
 */

/**
 * Implements hook_preprocess_page()
 */
function ckeditor_mentions_preprocess_page(&$variables) {
  backdrop_add_library('system', 'backdrop.ajax');
  $path = backdrop_get_path('module', 'ckeditor_mentions');
  backdrop_add_css($path . '/ckeditor_mentions.css');
  $create_links = config_get('ckeditor_mentions.settings', 'create_links');
  backdrop_add_js(array('MentionsCreateLinks' => $create_links), 'setting');
}

/**
 * Implements hook_menu().
 */
function ckeditor_mentions_menu() {
  $items['ckeditor/mentions'] = array(
    'title' => 'ajax callback ckeditor mentions',
    'page callback' => 'ckeditor_mentions_getpeople',
    'access arguments' => array('access user profiles'),
    'type' => MENU_CALLBACK,
    'delivery callback' => 'backdrop_json_output',
    'file' => 'includes/ckeditor_mentions.ajax.inc',
  );
  if (module_exists('mentions')) {
    $items['admin/config/content/mentions/ckeditor-mentions'] = array(
      'title' => 'CKEditor mentions settings',
      'page callback' => 'backdrop_get_form',
      'page arguments' => array('ckeditor_mentions_form'),
      'access arguments' => array('administer site configuration'),
      'type' => MENU_NORMAL_ITEM,
    );
  }
  else {
    $items['admin/config/content/ckeditor-mentions'] = array(
      'title' => 'Mentions',
      'page callback' => 'backdrop_get_form',
      'page arguments' => array('ckeditor_mentions_form'),
      'access arguments' => array('administer site configuration'),
      'type' => MENU_NORMAL_ITEM,
    );
  }
  return $items;
}

/**
 * Implements hook_ckeditor_plugin().
 */
function ckeditor_mentions_ckeditor_plugins() {
  $image_prefix = backdrop_get_path('module', 'ckeditor') . '/images/buttons/';
  return array('ckeditormentions' => array(
    'file' => 'plugin.js',
    'path' => backdrop_get_path('module', 'ckeditor_mentions') . '/plugins/mentions/',
    'enabled callback' => 'ckeditor_mentions_plugin_check',
    ));
}

function ckeditor_mentions_plugin_check($format, $plugin_name) {
  return TRUE;
}

/**
 * Implements hook_views_api().
 */
function ckeditor_mentions_views_api() {
  return array(
    'api' => '3.0',
    'path' => backdrop_get_path('module', 'ckeditor_mentions') . '/includes',
  );
}

/**
 * Page callback for mentions.
 */
function ckeditor_mentions_form($form, $form_state) {
  $create_links = config_get('ckeditor_mentions.settings', 'create_links');

  $form['#config'] = 'mentions.settings';
  $form['create_links'] = array(
    '#type' => 'checkbox',
    '#title' => t('Create links in editor'),
    '#description' => t('If checked, @mentions will be converted by Javascript to links within the Editor, otherwise they will be saved as @USERNAME without a link.'),
    '#default_value' => $create_links,
  );

  return system_settings_form($form);
}

/**
 * Implements hook_config_info().
 */
function ckeditor_mentions_config_info() {
  $prefixes['ckeditor_mentions.settings'] = array(
    'label' => t('CKEditor mentions settings'),
    'group' => t('Configuration'),
  );
}

