<?php

/**
 * @file
 * Defining ajax callbacks, registering CKEditor plugin and including default views.
 */

/**
 * Implements hook_preprocess_page()
 */
function ckeditor_mentions_preprocess_page(&$variables) {
  // We need to include our misc/ajax.js, else we can't be sure if it's included when we need it.
  backdrop_add_library('system', 'backdrop.ajax');
  $path = backdrop_get_path('module', 'ckeditor_mentions');
  backdrop_add_css($path . '/ckeditor_mentions.css');

}

/**
 * Implements hook_menu().
 */
function ckeditor_mentions_menu() {
  $items['ckeditor/mentions'] = array(
    'title' => 'ajax callback ckeditor mentions',
    'page callback' => 'ckeditor_mentions_getpeople',
    'access arguments' => array('access user profiles'),
    'type' => MENU_CALLBACK,
    'delivery callback' => 'backdrop_json_output',
    'file' => 'includes/ckeditor_mentions.ajax.inc',
  );
  return $items;
}

/**
 * Implements hook_ckeditor_plugin().
 */
function ckeditor_mentions_ckeditor_plugins() {
  $image_prefix = backdrop_get_path('module', 'ckeditor') . '/images/buttons/';
  return array('ckeditormentions' => array(
    //'name' => 'mentions',
    'file' => 'plugin.js',
    'path' => backdrop_get_path('module', 'ckeditor_mentions') . '/plugins/mentions/',
    'enabled callback' => 'ckeditor_mentions_plugin_check',
    ));
}

function ckeditor_mentions_plugin_check($format, $plugin_name) {
      return TRUE;
}

/**
 * Implements hook_views_api().
 */
function ckeditor_mentions_views_api() {
  return array(
    'api' => '3.0',
    'path' => backdrop_get_path('module', 'ckeditor_mentions') . '/includes',
  );
}
